---
name: Policy Remediation

parameters:
  - name: includeCanary
    displayName: Include Canary
    type: boolean
    default: false

trigger: none

schedules:
  - cron: "0 0 * * *"
    displayName: Daily at midnight
    branches:
      include:
        - main
    always: true
    batch: true

stages:
  - stage: remediate
    displayName: Remediate Policies
    condition: ${{ parameters.includeCanary }}
    jobs:
      - deployment: canary
        displayName: Canary
        variables:
          - template: ../../environments/canary/vars.yml
        pool:
          vmImage: ${{ variables.vmImage }}
        environment: Canary
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzurePowerShell@5
                  displayName: Remediate
                  inputs:
                    azureSubscription: ${{ variables.azureConnection }}
                    ScriptType: InlineScript
                    Inline: |
                      $(Build.SourcesDirectory)/modules/policies/scripts/Start-PolicyRemediation.ps1 -ManagementGroupId ${{ variables.managementGroupId }}
                    azurePowerShellVersion: LatestVersion
                    pwsh: true

      - deployment: prod
        displayName: Production
        variables:
          - template: ../../environments/prod/vars.yml
        pool:
          vmImage: ${{ variables.vmImage }}
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzurePowerShell@5
                  displayName: Remediate
                  inputs:
                    azureSubscription: ${{ variables.azureConnection }}
                    ScriptType: InlineScript
                    Inline: |
                      $(Build.SourcesDirectory)/modules/policies/scripts/Start-PolicyRemediation.ps1 -ManagementGroupId ${{ variables.managementGroupId }}
                    azurePowerShellVersion: LatestVersion
                    pwsh: true
...
