---
rules:
  braces:
    forbid: non-empty
    level: error
  brackets:
    forbid: true
    level: error
  colons:
    level: error
  commas:
    level: error
  comments:
    min-spaces-from-content: 1
    level: error
  comments-indentation:
    level: error
  document-end:
    present: false
    level: error
  document-start:
    present: true
    level: error
  empty-lines:
    max: 1
    level: error
  empty-values: disable
  hyphens:
    level: error
  indentation:
    spaces: 2
    level: error
  key-duplicates:
    level: error
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file:
    level: error
  new-lines:
    type: unix
    level: error
  octal-values: disable
  quoted-strings:
    quote-type: double
    required: only-when-needed
  trailing-spaces:
    level: error
  truthy:
    level: error
