name: AzureLandingZonesDemo/Management_Groups
on:
  push:
    paths:
    - ".azdo/pipelines/management-groups.yml"
    - environments/canary/management-groups.bicepparam
    - environments/prod/management-groups.bicepparam
    - modules/management-groups/**
    - "!README.md"
  pull_request:
    branches:
    - main
jobs:
  build-build:
    name: Build
    runs-on: ${{ env.vmImage }}
    env:
      azureConnection: root
      vmImage: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Build Template
      uses: azure/login@v1.6.0
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
    - name: Build Template
      run: |-
        az bicep build --file modules/management-groups/main.bicep --outfile ${{ runner.temp }}/main.json
        az bicep build-params --file environments/canary/management-groups.bicepparam --outfile ${{ runner.temp }}/main.canary.parameters.json
        az bicep build-params --file environments/prod/management-groups.bicepparam --outfile ${{ runner.temp }}/main.prod.parameters.json
      shell: bash
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4.1.0
      with:
        name: drop
        path: "${{ runner.temp }}"
  validate-canary:
    name: Canary
    needs:
    - build-build
    runs-on: ${{ env.vmImage }}
    environment:
      name: Canary
    env:
      azureConnection: root
      location: swedencentral
      logAnalyticsWorkspaceId: "/subscriptions/8228ddb9-d118-47b4-b4e7-1f1de7667d4d/resourceGroups/Management/providers/Microsoft.OperationalInsights/workspaces/ondfisklzcanary"
      managedIdentityId: "/subscriptions/8228ddb9-d118-47b4-b4e7-1f1de7667d4d/resourceGroups/Management/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ondfisklzcanary"
      managementGroupId: lz-canary
      policyAssignmentFolders: lz-canary, lz-canary/landing-zones/corp, lz-canary/landing-zones/online
      vmImage: ubuntu-latest
    if: success() && github.RUN_NUMBER == 1
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: download artifact
      uses: actions/download-artifact@v4.1.0
    - uses: "./.github/actions/azdo_pipelines_templates_tenant_deployment"
      with:
        displayName: Validate deployment
        deploymentName: management-groups
        command: validate
        azureConnection: "${{ env.azureConnection }}"
        location: "${{ env.location }}"
        templateFile: "${{ runner.workspace }}/drop/main.json"
        parameters: "${{ runner.workspace }}/drop/main.canary.parameters.json"
    - uses: "./.github/actions/azdo_pipelines_templates_tenant_deployment"
      with:
        displayName: What-if deployment
        deploymentName: management-groups
        command: what-if
        azureConnection: "${{ env.azureConnection }}"
        location: "${{ env.location }}"
        templateFile: "${{ runner.workspace }}/drop/main.json"
        parameters: "${{ runner.workspace }}/drop/main.canary.parameters.json"
  validate-prod:
    name: Production
    needs:
    - build-build
    runs-on: ${{ env.vmImage }}
    environment:
      name: Production
    env:
      azureConnection: root
      location: swedencentral
      logAnalyticsWorkspaceId: "/subscriptions/e678d35b-125e-41ad-ae35-c04dfd4162e5/resourceGroups/Management/providers/Microsoft.OperationalInsights/workspaces/ondfisklz"
      managedIdentityId: "/subscriptions/e678d35b-125e-41ad-ae35-c04dfd4162e5/resourceGroups/Management/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ondfisklz"
      managementGroupId: lz
      policyAssignmentFolders: lz, lz/landing-zones/corp, lz/landing-zones/online
      vmImage: ubuntu-latest
    if: github.RUN_NUMBER == 1
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: download artifact
      uses: actions/download-artifact@v4.1.0
    - uses: "./.github/actions/azdo_pipelines_templates_tenant_deployment"
      with:
        displayName: Validate deployment
        deploymentName: management-groups
        command: validate
        azureConnection: "${{ env.azureConnection }}"
        location: "${{ env.location }}"
        templateFile: "${{ runner.workspace }}/drop/main.json"
        parameters: "${{ runner.workspace }}/drop/main.prod.parameters.json"
    - uses: "./.github/actions/azdo_pipelines_templates_tenant_deployment"
      with:
        displayName: What-if deployment
        deploymentName: management-groups
        command: what-if
        azureConnection: "${{ env.azureConnection }}"
        location: "${{ env.location }}"
        templateFile: "${{ runner.workspace }}/drop/main.json"
        parameters: "${{ runner.workspace }}/drop/main.prod.parameters.json"
  deploy-canary:
    name: Canary
    needs:
    - validate-canary
    - validate-prod
    runs-on: ${{ env.vmImage }}
    environment:
      name: Canary
    env:
      azureConnection: root
      location: swedencentral
      logAnalyticsWorkspaceId: "/subscriptions/8228ddb9-d118-47b4-b4e7-1f1de7667d4d/resourceGroups/Management/providers/Microsoft.OperationalInsights/workspaces/ondfisklzcanary"
      managedIdentityId: "/subscriptions/8228ddb9-d118-47b4-b4e7-1f1de7667d4d/resourceGroups/Management/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ondfisklzcanary"
      managementGroupId: lz-canary
      policyAssignmentFolders: lz-canary, lz-canary/landing-zones/corp, lz-canary/landing-zones/online
      vmImage: ubuntu-latest
    if: success() && github.RUN_NUMBER == 1
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: download artifact
      uses: actions/download-artifact@v4.1.0
    - uses: "./.github/actions/azdo_pipelines_templates_tenant_deployment"
      with:
        displayName: Deploy management groups
        deploymentName: management-groups
        command: create
        azureConnection: "${{ env.azureConnection }}"
        location: "${{ env.location }}"
        templateFile: "${{ runner.workspace }}/drop/main.json"
        parameters: "${{ runner.workspace }}/drop/main.canary.parameters.json"
  deploy-prod:
    name: Production
    needs:
    - validate-canary
    - validate-prod
    runs-on: ${{ env.vmImage }}
    environment:
      name: Production
    env:
      azureConnection: root
      location: swedencentral
      logAnalyticsWorkspaceId: "/subscriptions/e678d35b-125e-41ad-ae35-c04dfd4162e5/resourceGroups/Management/providers/Microsoft.OperationalInsights/workspaces/ondfisklz"
      managedIdentityId: "/subscriptions/e678d35b-125e-41ad-ae35-c04dfd4162e5/resourceGroups/Management/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ondfisklz"
      managementGroupId: lz
      policyAssignmentFolders: lz, lz/landing-zones/corp, lz/landing-zones/online
      vmImage: ubuntu-latest
    if: (success() && github.ref == 'refs/heads/main') && github.RUN_NUMBER == 1
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: download artifact
      uses: actions/download-artifact@v4.1.0
    - uses: "./.github/actions/azdo_pipelines_templates_tenant_deployment"
      with:
        displayName: Deploy management groups
        deploymentName: management-groups
        command: create
        azureConnection: "${{ env.azureConnection }}"
        location: "${{ env.location }}"
        templateFile: "${{ runner.workspace }}/drop/main.json"
        parameters: "${{ runner.workspace }}/drop/main.prod.parameters.json"
