name: AzureLandingZonesDemo/Policy_Remediation
on:
  workflow_dispatch:
    inputs:
      includeCanary:
        description: Include Canary
        default: false
        type: boolean
        required: false
  pull_request:
    branches:
    - defender-benchmark
  # Github Actions does not support schedule branch filters. Scheduled workflows run on the latest commit on the default or base branch
  schedule:
  - cron: 0 0 * * *
jobs:
  canary:
    name: Canary
    runs-on: ${{ env.vmImage }}
    environment:
      name: Canary
    env:
      azureConnection: root
      location: swedencentral
      logAnalyticsWorkspaceId: "/subscriptions/8228ddb9-d118-47b4-b4e7-1f1de7667d4d/resourceGroups/Management/providers/Microsoft.OperationalInsights/workspaces/ondfisklzcanary"
      managedIdentityId: "/subscriptions/8228ddb9-d118-47b4-b4e7-1f1de7667d4d/resourceGroups/Management/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ondfisklzcanary"
      managementGroupId: lz-canary
      policyAssignmentFolders: lz-canary, lz-canary/landing-zones/corp, lz-canary/landing-zones/online
      vmImage: ubuntu-latest
    if: inputs.includeCanary && github.RUN_NUMBER == 1
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: download artifact
      uses: actions/download-artifact@v4.1.0
    - uses: actions/checkout@v4.1.0
    - name: Remediate
      uses: azure/login@v1.6.0
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
        enable-AzPSSession: true
    - name: Remediate
      uses: azure/powershell@v1.4.0
      with:
        inlineScript: "${{ github.workspace }}/modules/policies/scripts/Start-PolicyRemediation.ps1 -ManagementGroupId ${{ env.managementGroupId }}"
        errorActionPreference: Stop
        failOnStandardError: false
        azPSVersion: latest
  prod:
    name: Production
    runs-on: ${{ env.vmImage }}
    environment:
      name: Production
    env:
      azureConnection: root
      location: swedencentral
      logAnalyticsWorkspaceId: "/subscriptions/e678d35b-125e-41ad-ae35-c04dfd4162e5/resourceGroups/Management/providers/Microsoft.OperationalInsights/workspaces/ondfisklz"
      managedIdentityId: "/subscriptions/e678d35b-125e-41ad-ae35-c04dfd4162e5/resourceGroups/Management/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ondfisklz"
      managementGroupId: lz
      policyAssignmentFolders: lz, lz/landing-zones/corp, lz/landing-zones/online
      vmImage: ubuntu-latest
    if: inputs.includeCanary && github.RUN_NUMBER == 1
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: download artifact
      uses: actions/download-artifact@v4.1.0
    - uses: actions/checkout@v4.1.0
    - name: Remediate
      uses: azure/login@v1.6.0
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
        enable-AzPSSession: true
    - name: Remediate
      uses: azure/powershell@v1.4.0
      with:
        inlineScript: "${{ github.workspace }}/modules/policies/scripts/Start-PolicyRemediation.ps1 -ManagementGroupId ${{ env.managementGroupId }}"
        errorActionPreference: Stop
        failOnStandardError: false
        azPSVersion: latest
